services:
  - type: web
    name: drwpp-canvas-mvp
    runtime: node
    plan: free
    buildCommand: ./deploy.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
